## The nn Module


In [2]:
# create model class
import torch 
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [3]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6004],
        [0.6051],
        [0.5878],
        [0.6375],
        [0.6012],
        [0.5639],
        [0.6141],
        [0.6033],
        [0.5825],
        [0.5830]], grad_fn=<SigmoidBackward0>)

In [4]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.2242, -0.0049,  0.1320, -0.1884,  0.2444]], requires_grad=True)

In [5]:
# show model bias
model.linear.bias

Parameter containing:
tensor([0.1369], requires_grad=True)

In [6]:
from torchinfo import summary

In [7]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Creating Simple Neural Network

In [8]:
class simpleNN(nn.Module):
    def __init__(self, num_features):
       super().__init__()
       self.linear1 = nn.Linear(num_features,3)
       self.relu = nn.ReLU()
       self.linear2 = nn.Linear(3,1)
       self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [9]:
# create dataset
features = torch.rand(10,5)

# create model
model = simpleNN(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.3390],
        [0.3320],
        [0.3296],
        [0.3228],
        [0.3249],
        [0.3293],
        [0.3166],
        [0.3197],
        [0.3281],
        [0.3219]], grad_fn=<SigmoidBackward0>)

In [10]:
model.linear1.weight

Parameter containing:
tensor([[-0.3306,  0.1132, -0.0903, -0.1143, -0.0431],
        [-0.4212, -0.1587,  0.3960, -0.2200, -0.3596],
        [ 0.1723,  0.1374,  0.1644, -0.2146,  0.1245]], requires_grad=True)

In [11]:
model.linear2.weight

Parameter containing:
tensor([[ 0.0189,  0.2100, -0.3915]], requires_grad=True)

In [12]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
simpleNN                                 [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Using nn.Sequential

In [13]:
class simpleNN(nn.Module):
    def __init__(self, num_features):
       super().__init__()
       self.network = nn.Sequential(
                nn.Linear(num_features,3),
                nn.ReLU(),
                nn.Linear(3,1),
                nn.Sigmoid())
    
    def forward(self, features):
        out = self.network(features)
        return out

In [14]:
# create dataset
features = torch.rand(10,5)
# create model
model = simpleNN(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6230],
        [0.6230],
        [0.6230],
        [0.6253],
        [0.6230],
        [0.6230],
        [0.6262],
        [0.6261],
        [0.6230],
        [0.6349]], grad_fn=<SigmoidBackward0>)

In [15]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
simpleNN                                 [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Training Model Using Dataset

In [16]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [17]:
csv_file_path = fr"C:\Users\sanje\Desktop\Python_Frameworks_For_Machine_Learning\datafiles\breast_cancer_dataset.csv"
df =pd.read_csv(csv_file_path)

In [18]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [19]:
df.drop(columns=['id'], inplace = True)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [21]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [22]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [23]:
X_train_tensor = torch.from_numpy(X_train).to(torch.float32)
X_test_tensor = torch.from_numpy(X_test).to(torch.float32)
y_train_tensor = torch.from_numpy(y_train).to(torch.float32)
y_test_tensor = torch.from_numpy(y_test).to(torch.float32)

In [24]:
X_train_tensor.shape

torch.Size([455, 30])

In [25]:
X_train_tensor.dtype

torch.float32

In [26]:
y_train_tensor.shape

torch.Size([455])

In [27]:
y_train_tensor.dtype

torch.float32

In [28]:
class mySimpleNN(nn.Module):
    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    
        # Binary Cross Entropy Loss Function
    def binary_cross_entropy_loss(self, prediction, target):
        epsilon = 1e-8 # To prevent log(0)
        prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
        return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction)).mean()


In [29]:
learning_rate = 0.01
epochs = 2000

In [30]:
# create model
model = mySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

   # forward pass
   y_pred = model(X_train_tensor)

   # loss calculate
   loss = model.binary_cross_entropy_loss(y_pred,y_train_tensor)
   

   # backward pass
   loss.backward()

   # parameters update
   with torch.no_grad():   # disable gradient tracking
      model.linear.weight -= learning_rate * model.linear.weight.grad
      model.linear.bias -= learning_rate * model.linear.bias.grad
   
   # zero gradients -> clearing gradients which prevents gradient accumulation

   model.linear.weight.grad.zero_()
   model.linear.bias.grad.zero_()

   # print loss in each epoch
   print(f"Epoch: {epoch+1}, Loss:{loss.item()}")


Epoch: 1, Loss:0.7088890075683594
Epoch: 2, Loss:0.7079430818557739
Epoch: 3, Loss:0.707045316696167
Epoch: 4, Loss:0.7061929702758789
Epoch: 5, Loss:0.7053834199905396
Epoch: 6, Loss:0.7046142816543579
Epoch: 7, Loss:0.7038832902908325
Epoch: 8, Loss:0.7031883001327515
Epoch: 9, Loss:0.7025273442268372
Epoch: 10, Loss:0.7018982172012329
Epoch: 11, Loss:0.7012993693351746
Epoch: 12, Loss:0.7007287740707397
Epoch: 13, Loss:0.7001848816871643
Epoch: 14, Loss:0.6996662616729736
Epoch: 15, Loss:0.6991713047027588
Epoch: 16, Loss:0.6986985802650452
Epoch: 17, Loss:0.6982468962669373
Epoch: 18, Loss:0.69781494140625
Epoch: 19, Loss:0.6974016427993774
Epoch: 20, Loss:0.6970058083534241
Epoch: 21, Loss:0.6966263651847839
Epoch: 22, Loss:0.696262538433075
Epoch: 23, Loss:0.6959131360054016
Epoch: 24, Loss:0.6955775022506714
Epoch: 25, Loss:0.6952548027038574
Epoch: 26, Loss:0.6949442028999329
Epoch: 27, Loss:0.6946450471878052
Epoch: 28, Loss:0.6943566799163818
Epoch: 29, Loss:0.694078385829925

## Use of torch.optim and Loss Function of nn.Module

In [31]:
class mySimpleNN(nn.Module):
    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [32]:
# define loss function
loss_function = nn.BCELoss()

In [33]:
# create model
model = mySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

# define loop
for epoch in range(epochs):

   # forward pass
   y_pred = model(X_train_tensor)

   # loss calculate
   loss = loss_function(y_pred,y_train_tensor.view(-1,1))
   
   # zero gradients -> clearing gradients which prevents gradient accumulation
   optimizer.zero_grad()
   
   # backward pass
   loss.backward()

   # parameters update
   optimizer.step()


   # print loss in each epoch
   print(f"Epoch: {epoch+1}, Loss:{loss.item()}")


Epoch: 1, Loss:1.064510703086853
Epoch: 2, Loss:1.026534914970398
Epoch: 3, Loss:0.990484893321991
Epoch: 4, Loss:0.9563264846801758
Epoch: 5, Loss:0.9240128397941589
Epoch: 6, Loss:0.8934869170188904
Epoch: 7, Loss:0.8646823167800903
Epoch: 8, Loss:0.8375257849693298
Epoch: 9, Loss:0.8119387626647949
Epoch: 10, Loss:0.7878392338752747
Epoch: 11, Loss:0.7651434540748596
Epoch: 12, Loss:0.7437671422958374
Epoch: 13, Loss:0.7236275672912598
Epoch: 14, Loss:0.7046434879302979
Epoch: 15, Loss:0.686737060546875
Epoch: 16, Loss:0.6698340773582458
Epoch: 17, Loss:0.6538641452789307
Epoch: 18, Loss:0.6387614011764526
Epoch: 19, Loss:0.624464213848114
Epoch: 20, Loss:0.6109155416488647
Epoch: 21, Loss:0.59806227684021
Epoch: 22, Loss:0.5858557224273682
Epoch: 23, Loss:0.5742508172988892
Epoch: 24, Loss:0.5632059574127197
Epoch: 25, Loss:0.5526831150054932
Epoch: 26, Loss:0.5426473021507263
Epoch: 27, Loss:0.5330662727355957
Epoch: 28, Loss:0.5239104628562927
Epoch: 29, Loss:0.5151525735855103
E

In [34]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")


Accuracy: 0.5392428636550903
