## The nn Module


In [1]:
# create model class
import torch 
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [2]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.7005],
        [0.5714],
        [0.6547],
        [0.6606],
        [0.6276],
        [0.5323],
        [0.6233],
        [0.6148],
        [0.5934],
        [0.6050]], grad_fn=<SigmoidBackward0>)

In [3]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.4364,  0.2056,  0.2494,  0.2805,  0.4098]], requires_grad=True)

In [4]:
# show model bias
model.linear.bias

Parameter containing:
tensor([0.2323], requires_grad=True)

In [5]:
from torchinfo import summary

In [6]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Creating Simple Neural Network

In [7]:
class simpleNN(nn.Module):
    def __init__(self, num_features):
       super().__init__()
       self.linear1 = nn.Linear(num_features,3)
       self.relu = nn.ReLU()
       self.linear2 = nn.Linear(3,1)
       self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [8]:
# create dataset
features = torch.rand(10,5)

# create model
model = simpleNN(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6453],
        [0.6532],
        [0.6487],
        [0.6632],
        [0.6660],
        [0.6608],
        [0.6721],
        [0.6354],
        [0.6695],
        [0.6534]], grad_fn=<SigmoidBackward0>)

In [9]:
model.linear1.weight

Parameter containing:
tensor([[-0.0558,  0.2443,  0.0232,  0.3338, -0.3682],
        [-0.0587, -0.1234,  0.1329,  0.4335,  0.3373],
        [-0.2310, -0.0042, -0.0094, -0.2698,  0.1458]], requires_grad=True)

In [10]:
model.linear2.weight

Parameter containing:
tensor([[ 0.3924, -0.0946,  0.2719]], requires_grad=True)

In [11]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
simpleNN                                 [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Using nn.Sequential

In [12]:
class simpleNN(nn.Module):
    def __init__(self, num_features):
       super().__init__()
       self.network = nn.Sequential(
                nn.Linear(num_features,3),
                nn.ReLU(),
                nn.Linear(3,1),
                nn.Sigmoid())
    
    def forward(self, features):
        out = self.network(features)
        return out

In [13]:
# create dataset
features = torch.rand(10,5)
# create model
model = simpleNN(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.3622],
        [0.3624],
        [0.3386],
        [0.3625],
        [0.3456],
        [0.3456],
        [0.3622],
        [0.3543],
        [0.3272],
        [0.3161]], grad_fn=<SigmoidBackward0>)

In [14]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
simpleNN                                 [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Training Model Using Dataset

In [15]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [16]:
csv_file_path = fr"C:\Users\sanje\Desktop\Python_Frameworks_For_Machine_Learning\datafiles\breast_cancer_dataset.csv"
df =pd.read_csv(csv_file_path)

In [17]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [18]:
df.drop(columns=['id'], inplace = True)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [20]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [21]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [22]:
X_train_tensor = torch.from_numpy(X_train).to(torch.float32)
X_test_tensor = torch.from_numpy(X_test).to(torch.float32)
y_train_tensor = torch.from_numpy(y_train).to(torch.float32)
y_test_tensor = torch.from_numpy(y_test).to(torch.float32)

In [23]:
X_test_tensor.shape

torch.Size([114, 30])

In [24]:
X_train_tensor.dtype

torch.float32

In [25]:
y_train_tensor.shape

torch.Size([455])

In [26]:
y_train_tensor.dtype

torch.float32

In [27]:
class mySimpleNN(nn.Module):
    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    
        # Binary Cross Entropy Loss Function
    def binary_cross_entropy_loss(self, prediction, target):
        epsilon = 1e-8 # To prevent log(0)
        prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
        return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction)).mean()


In [28]:
learning_rate = 0.01
epochs = 2000

In [29]:
# create model
model = mySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

   # forward pass
   y_pred = model(X_train_tensor)

   # loss calculate
   loss = model.binary_cross_entropy_loss(y_pred,y_train_tensor)
   

   # backward pass
   loss.backward()

   # parameters update
   with torch.no_grad():   # disable gradient tracking
      model.linear.weight -= learning_rate * model.linear.weight.grad
      model.linear.bias -= learning_rate * model.linear.bias.grad
   
   # zero gradients -> clearing gradients which prevents gradient accumulation

   model.linear.weight.grad.zero_()
   model.linear.bias.grad.zero_()

   # print loss in each epoch
   print(f"Epoch: {epoch+1}, Loss:{loss.item()}")


Epoch: 1, Loss:0.7074537873268127
Epoch: 2, Loss:0.7071073651313782
Epoch: 3, Loss:0.7067687511444092
Epoch: 4, Loss:0.706437349319458
Epoch: 5, Loss:0.7061128616333008
Epoch: 6, Loss:0.7057950496673584
Epoch: 7, Loss:0.7054835557937622
Epoch: 8, Loss:0.7051779627799988
Epoch: 9, Loss:0.7048780918121338
Epoch: 10, Loss:0.7045838236808777
Epoch: 11, Loss:0.7042946815490723
Epoch: 12, Loss:0.7040106058120728
Epoch: 13, Loss:0.7037312984466553
Epoch: 14, Loss:0.703456461429596
Epoch: 15, Loss:0.7031861543655396
Epoch: 16, Loss:0.7029199600219727
Epoch: 17, Loss:0.7026576399803162
Epoch: 18, Loss:0.7023993134498596
Epoch: 19, Loss:0.7021446824073792
Epoch: 20, Loss:0.7018936276435852
Epoch: 21, Loss:0.7016459107398987
Epoch: 22, Loss:0.7014015316963196
Epoch: 23, Loss:0.7011602520942688
Epoch: 24, Loss:0.7009220719337463
Epoch: 25, Loss:0.7006868124008179
Epoch: 26, Loss:0.7004545331001282
Epoch: 27, Loss:0.7002248167991638
Epoch: 28, Loss:0.6999979019165039
Epoch: 29, Loss:0.6997734308242

## Use of torch.optim and Loss Function of nn.Module

In [30]:
class mySimpleNN(nn.Module):
    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [31]:
# define loss function
loss_function = nn.BCELoss()

In [32]:
# create model
model = mySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

# define loop
for epoch in range(epochs):

   # forward pass
   y_pred = model(X_train_tensor)

   # loss calculate
   loss = loss_function(y_pred,y_train_tensor.view(-1,1))
   
   # zero gradients -> clearing gradients which prevents gradient accumulation
   optimizer.zero_grad()
   
   # backward pass
   loss.backward()

   # parameters update
   optimizer.step()


   # print loss in each epoch
   print(f"Epoch: {epoch+1}, Loss:{loss.item()}")


Epoch: 1, Loss:0.5234535932540894
Epoch: 2, Loss:0.514359176158905
Epoch: 3, Loss:0.5057007670402527
Epoch: 4, Loss:0.49744781851768494
Epoch: 5, Loss:0.4895721971988678
Epoch: 6, Loss:0.4820482134819031
Epoch: 7, Loss:0.4748522937297821
Epoch: 8, Loss:0.4679631292819977
Epoch: 9, Loss:0.4613606631755829
Epoch: 10, Loss:0.4550268054008484
Epoch: 11, Loss:0.4489450454711914
Epoch: 12, Loss:0.44309982657432556
Epoch: 13, Loss:0.4374772012233734
Epoch: 14, Loss:0.43206387758255005
Epoch: 15, Loss:0.4268479645252228
Epoch: 16, Loss:0.42181825637817383
Epoch: 17, Loss:0.41696441173553467
Epoch: 18, Loss:0.41227689385414124
Epoch: 19, Loss:0.4077467918395996
Epoch: 20, Loss:0.40336573123931885
Epoch: 21, Loss:0.39912620186805725
Epoch: 22, Loss:0.39502090215682983
Epoch: 23, Loss:0.39104318618774414
Epoch: 24, Loss:0.38718676567077637
Epoch: 25, Loss:0.3834458291530609
Epoch: 26, Loss:0.37981489300727844
Epoch: 27, Loss:0.3762888014316559
Epoch: 28, Loss:0.3728628158569336
Epoch: 29, Loss:0.

In [33]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")


Accuracy: 0.5497075915336609
