## The nn Module


In [1]:
# create model class
import torch 
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [2]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.7090],
        [0.6750],
        [0.5935],
        [0.6685],
        [0.6428],
        [0.7102],
        [0.6099],
        [0.6674],
        [0.7205],
        [0.6045]], grad_fn=<SigmoidBackward0>)

In [3]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[0.4372, 0.1422, 0.1972, 0.2204, 0.1353]], requires_grad=True)

In [4]:
# show model bias
model.linear.bias

Parameter containing:
tensor([0.1115], requires_grad=True)

In [5]:
from torchinfo import summary

In [6]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Creating Simple Neural Network

In [7]:
class simpleNN(nn.Module):
    def __init__(self, num_features):
       super().__init__()
       self.linear1 = nn.Linear(num_features,3)
       self.relu = nn.ReLU()
       self.linear2 = nn.Linear(3,1)
       self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [8]:
# create dataset
features = torch.rand(10,5)

# create model
model = simpleNN(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5059],
        [0.5082],
        [0.5082],
        [0.5082],
        [0.4799],
        [0.5082],
        [0.5082],
        [0.5082],
        [0.4960],
        [0.5082]], grad_fn=<SigmoidBackward0>)

In [9]:
model.linear1.weight

Parameter containing:
tensor([[ 0.0284, -0.3417, -0.1825, -0.3766, -0.0545],
        [ 0.0987,  0.4145,  0.3391, -0.0686, -0.2675],
        [-0.4249,  0.1988, -0.2815, -0.1440,  0.1073]], requires_grad=True)

In [10]:
model.linear2.weight

Parameter containing:
tensor([[-0.0622, -0.4170,  0.3284]], requires_grad=True)

In [11]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
simpleNN                                 [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Using nn.Sequential

In [12]:
class simpleNN(nn.Module):
    def __init__(self, num_features):
       super().__init__()
       self.network = nn.Sequential(
                nn.Linear(num_features,3),
                nn.ReLU(),
                nn.Linear(3,1),
                nn.Sigmoid())
    
    def forward(self, features):
        out = self.network(features)
        return out

In [13]:
# create dataset
features = torch.rand(10,5)
# create model
model = simpleNN(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6801],
        [0.6713],
        [0.6636],
        [0.6277],
        [0.6208],
        [0.6566],
        [0.6581],
        [0.6292],
        [0.6765],
        [0.6357]], grad_fn=<SigmoidBackward0>)

In [14]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
simpleNN                                 [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Training Model Using Dataset

In [15]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [16]:
csv_file_path = fr"C:\Users\sanje\Desktop\Python_Frameworks_For_Machine_Learning\datafiles\breast_cancer_dataset.csv"
df =pd.read_csv(csv_file_path)

In [17]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [18]:
df.drop(columns=['id'], inplace = True)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [20]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [21]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [22]:
X_train_tensor = torch.from_numpy(X_train).to(torch.float32)
X_test_tensor = torch.from_numpy(X_test).to(torch.float32)
y_train_tensor = torch.from_numpy(y_train).to(torch.float32)
y_test_tensor = torch.from_numpy(y_test).to(torch.float32)

In [23]:
X_test_tensor.shape

torch.Size([114, 30])

In [24]:
X_train_tensor.dtype

torch.float32

In [25]:
y_train_tensor.shape

torch.Size([455])

In [26]:
y_train_tensor.dtype

torch.float32

In [27]:
class mySimpleNN(nn.Module):
    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    
        # Binary Cross Entropy Loss Function
    def binary_cross_entropy_loss(self, prediction, target):
        epsilon = 1e-8 # To prevent log(0)
        prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
        return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction)).mean()


In [28]:
learning_rate = 0.01
epochs = 2000

In [29]:
# create model
model = mySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

   # forward pass
   y_pred = model(X_train_tensor)

   # loss calculate
   loss = model.binary_cross_entropy_loss(y_pred,y_train_tensor)
   

   # backward pass
   loss.backward()

   # parameters update
   with torch.no_grad():   # disable gradient tracking
      model.linear.weight -= learning_rate * model.linear.weight.grad
      model.linear.bias -= learning_rate * model.linear.bias.grad
   
   # zero gradients -> clearing gradients which prevents gradient accumulation

   model.linear.weight.grad.zero_()
   model.linear.bias.grad.zero_()

   # print loss in each epoch
   print(f"Epoch: {epoch+1}, Loss:{loss.item()}")


Epoch: 1, Loss:0.7407342195510864
Epoch: 2, Loss:0.7396909594535828
Epoch: 3, Loss:0.7386786937713623
Epoch: 4, Loss:0.7376959919929504
Epoch: 5, Loss:0.7367414832115173
Epoch: 6, Loss:0.7358139753341675
Epoch: 7, Loss:0.7349122166633606
Epoch: 8, Loss:0.7340351939201355
Epoch: 9, Loss:0.7331818342208862
Epoch: 10, Loss:0.7323510050773621
Epoch: 11, Loss:0.7315417528152466
Epoch: 12, Loss:0.7307533621788025
Epoch: 13, Loss:0.7299848198890686
Epoch: 14, Loss:0.7292352914810181
Epoch: 15, Loss:0.728503942489624
Epoch: 16, Loss:0.7277899980545044
Epoch: 17, Loss:0.7270929217338562
Epoch: 18, Loss:0.7264119386672974
Epoch: 19, Loss:0.7257464528083801
Epoch: 20, Loss:0.7250956892967224
Epoch: 21, Loss:0.7244592308998108
Epoch: 22, Loss:0.7238364815711975
Epoch: 23, Loss:0.7232269644737244
Epoch: 24, Loss:0.7226300239562988
Epoch: 25, Loss:0.722045361995697
Epoch: 26, Loss:0.721472442150116
Epoch: 27, Loss:0.7209107279777527
Epoch: 28, Loss:0.7203601002693176
Epoch: 29, Loss:0.71981990337371

## Use of torch.optim and Loss Function of nn.Module

In [30]:
# define loss function
loss_function = nn.BCELoss()

In [ ]:
# create model
model = mySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

# define loop
for epoch in range(epochs):

   # forward pass
   y_pred = model(X_train_tensor)

   # loss calculate
   loss = loss_function(y_pred,y_train_tensor.view(-1,1))
   
   # zero gradients -> clearing gradients which prevents gradient accumulation
   optimizer.zero_grad()
   
   # backward pass
   loss.backward()

   # parameters update
   optimizer.step()


   # print loss in each epoch
   print(f"Epoch: {epoch+1}, Loss:{loss.item()}")


Epoch: 1, Loss:0.85545814037323
Epoch: 2, Loss:0.8276238441467285
Epoch: 3, Loss:0.8014765381813049
Epoch: 4, Loss:0.7769266963005066
Epoch: 5, Loss:0.7538805603981018
Epoch: 6, Loss:0.7322433590888977
Epoch: 7, Loss:0.7119209170341492
Epoch: 8, Loss:0.6928222179412842
Epoch: 9, Loss:0.6748599410057068
Epoch: 10, Loss:0.6579515933990479
Epoch: 11, Loss:0.6420196890830994
Epoch: 12, Loss:0.6269917488098145
Epoch: 13, Loss:0.6128008961677551
Epoch: 14, Loss:0.5993850231170654
Epoch: 15, Loss:0.5866870284080505
Epoch: 16, Loss:0.5746544599533081
Epoch: 17, Loss:0.5632389187812805
Epoch: 18, Loss:0.5523962378501892
Epoch: 19, Loss:0.5420858263969421
Epoch: 20, Loss:0.5322705507278442
Epoch: 21, Loss:0.5229162573814392
Epoch: 22, Loss:0.5139918327331543
Epoch: 23, Loss:0.505468487739563
Epoch: 24, Loss:0.4973199665546417
Epoch: 25, Loss:0.4895220696926117
Epoch: 26, Loss:0.48205262422561646
Epoch: 27, Loss:0.47489115595817566
Epoch: 28, Loss:0.4680188000202179
Epoch: 29, Loss:0.461418241262

In [32]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")


Accuracy: 0.5240073800086975
