## Importing Libraries And Dataset

In [103]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [104]:
csv_file_path = fr"C:\Users\sanje\Desktop\Python_Frameworks_For_Machine_Learning\datafiles\breast_cancer_dataset.csv"
df =pd.read_csv(csv_file_path)

In [105]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [106]:
df.shape

(569, 32)

In [107]:
df.drop(columns=['id'], inplace = True)

In [108]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## Train Test Split

In [109]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

## Normalization


In [110]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
391        8.734         16.84           55.27      234.3          0.10390   
418       12.700         12.17           80.88      495.0          0.08785   
231       11.320         27.08           71.76      395.7          0.06883   
41        10.950         21.35           71.90      371.1          0.12270   
147       14.950         18.77           97.84      689.5          0.08138   
..           ...           ...             ...        ...              ...   
101        6.981         13.43           43.79      143.5          0.11700   
111       12.630         20.76           82.15      480.4          0.09933   
146       11.800         16.58           78.99      432.0          0.10910   
48        12.050         14.63           78.04      449.3          0.10310   
64        12.680         23.84           82.69      499.0          0.11220   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
391           0.07428         0.00000             0.000000         0.1985   
418           0.05794         0.02360             0.024020         0.1583   
231           0.03813         0.01633             0.003125         0.1869   
41            0.12180         0.10440             0.056690         0.1895   
147           0.11670         0.09050             0.035620         0.1744   
..                ...             ...                  ...            ...   
101           0.07568         0.00000             0.000000         0.1930   
111           0.12090         0.10650             0.060210         0.1735   
146           0.17000         0.16590             0.074150         0.2678   
48            0.09092         0.06592             0.027490         0.1675   
64            0.12620         0.11280             0.068730         0.1905   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
391                 0.07098  ...         10.17          22.80   
418                 0.06275  ...         13.65          16.92   
231                 0.05628  ...         12.08          33.75   
41                  0.06870  ...         12.84          35.34   
147                 0.06493  ...         16.25          25.47   
..                      ...  ...           ...            ...   
101                 0.07818  ...          7.93          19.54   
111                 0.07070  ...         13.33          25.47   
146                 0.07371  ...         13.74          26.38   
48                  0.06043  ...         13.76          20.70   
64                  0.06590  ...         17.09          33.47   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
391            64.01       317.0           0.14600             0.1310   
418            88.12       566.9           0.13140             0.1607   
231            79.82       452.3           0.09203             0.1432   
41             87.22       514.0           0.19090             0.2698   
147           107.10       809.7           0.09970             0.2521   
..               ...         ...               ...                ...   
101            50.41       185.2           0.15840             0.1202   
111            89.00       527.4           0.12870             0.2250   
146            91.93       591.7           0.13850             0.4092   
48             89.88       582.6           0.14940             0.2156   
64            111.80       888.3           0.18510             0.4061   

     concavity_worst  concave points_worst  symmetry_worst  \
391          0.00000               0.00000          0.2445   
418          0.09385               0.08224          0.2775   
231          0.10890               0.02083          0.2849   
41           0.40230               0.14240          0.2964   
147          0.25000               0.08405          0.2852   
..               ...                   ...             ...   
101          0.00000               0.00000         

In [111]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [112]:
X_train

array([[-1.54970536, -0.56848076, -1.53006357, ..., -1.78852851,
        -0.78354959,  0.26015255],
       [-0.42621235, -1.6406961 , -0.4771967 , ..., -0.51401716,
        -0.2279863 ,  0.5930271 ],
       [-0.81714033,  1.7825867 , -0.85213406, ..., -1.46571636,
        -0.10340544, -0.72791247],
       ...,
       [-0.68116538, -0.62817584, -0.55489754, ...,  1.10174833,
         4.82090555,  1.05760661],
       [-0.6103451 , -1.07588888, -0.59395351, ..., -0.77375464,
        -0.27512501, -0.0532719 ],
       [-0.43187798,  1.03869426, -0.40278479, ...,  0.87083613,
         0.79559697,  1.06316378]], shape=(455, 30))

## Label Encoding

In [113]:
y_train

391    B
418    B
231    B
41     M
147    B
      ..
101    B
111    B
146    M
48     B
64     M
Name: diagnosis, Length: 455, dtype: object

In [114]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [115]:
y_train

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

## NumPy Arrays To Pytoch Tensors

In [116]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [117]:
X_train_tensor

tensor([[-1.5497, -0.5685, -1.5301,  ..., -1.7885, -0.7835,  0.2602],
        [-0.4262, -1.6407, -0.4772,  ..., -0.5140, -0.2280,  0.5930],
        [-0.8171,  1.7826, -0.8521,  ..., -1.4657, -0.1034, -0.7279],
        ...,
        [-0.6812, -0.6282, -0.5549,  ...,  1.1017,  4.8209,  1.0576],
        [-0.6103, -1.0759, -0.5940,  ..., -0.7738, -0.2751, -0.0533],
        [-0.4319,  1.0387, -0.4028,  ...,  0.8708,  0.7956,  1.0632]],
       dtype=torch.float64)

In [118]:
X_train_tensor.shape

torch.Size([455, 30])

In [119]:
y_train_tensor

tensor([0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
        1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
        0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
        1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
        0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
        1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,

In [120]:
y_train_tensor.shape

torch.Size([455])

## Defining A Model

In [121]:
class MySimpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad = True)
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)
    
    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    # Binary Cross Entropy Loss Function
    def binary_cross_entropy_loss(self, prediction, target):
        epsilon = 1e-8 # To prevent log(0)
        prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
        return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction)).mean()

## Important Parameters

In [127]:
learning_rate = 0.01
epochs = 2000

## Training Pipeline

In [128]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

   # forward pass
   y_pred = model.forward(X_train_tensor)

   # loss calculate
   loss = model.binary_cross_entropy_loss(y_pred,y_train_tensor)
   

   # backward pass
   loss.backward()

   # parameters update
   with torch.no_grad():   # disable gradient tracking
      model.weights -= learning_rate * model.weights.grad
      model.bias -= learning_rate * model.bias.grad
   
   # zero gradients -> clearing gradients which prevents gradient accumulation

   model.weights.grad.zero_()
   model.bias.grad.zero_()

   # print loss in each epoch
   print(f"Epoch: {epoch+1}, Loss:{loss.item()}")


Epoch: 1, Loss:3.4369277020122135
Epoch: 2, Loss:3.4220244185650066
Epoch: 3, Loss:3.4071371100717656
Epoch: 4, Loss:3.392265986737074
Epoch: 5, Loss:3.3774112602925235
Epoch: 6, Loss:3.3625731439547297
Epoch: 7, Loss:3.347751852354391
Epoch: 8, Loss:3.33294760151501
Epoch: 9, Loss:3.3181606088490425
Epoch: 10, Loss:3.303391093063104
Epoch: 11, Loss:3.288634019019264
Epoch: 12, Loss:3.2735916485945453
Epoch: 13, Loss:3.258387553245405
Epoch: 14, Loss:3.2432021206031116
Epoch: 15, Loss:3.2280355845685667
Epoch: 16, Loss:3.212888180412788
Epoch: 17, Loss:3.197760144775483
Epoch: 18, Loss:3.1826517157552385
Epoch: 19, Loss:3.167563132884255
Epoch: 20, Loss:3.1524946371418516
Epoch: 21, Loss:3.1374464709716445
Epoch: 22, Loss:3.1224188783445195
Epoch: 23, Loss:3.1074121047956496
Epoch: 24, Loss:3.092386447152149
Epoch: 25, Loss:3.0772014446526614
Epoch: 26, Loss:3.06203806938897
Epoch: 27, Loss:3.046896577215278
Epoch: 28, Loss:3.031703286151201
Epoch: 29, Loss:3.0162645100951524
Epoch: 30

In [129]:
model.weights

tensor([[-0.0121],
        [-0.0086],
        [ 0.2362],
        [-0.2108],
        [ 0.1678],
        [ 0.2302],
        [ 0.0306],
        [-0.4417],
        [-0.0716],
        [ 0.1141],
        [-0.0399],
        [-0.0381],
        [-0.2622],
        [ 0.2386],
        [ 0.0853],
        [-0.2307],
        [ 0.0905],
        [ 0.1576],
        [ 0.0934],
        [-0.1267],
        [ 0.0816],
        [ 0.0720],
        [-0.0595],
        [ 0.2139],
        [-0.2693],
        [ 0.0976],
        [-0.1489],
        [ 0.1154],
        [-0.0327],
        [ 0.0925]], dtype=torch.float64, requires_grad=True)

In [130]:
model.bias

tensor([-0.4698], dtype=torch.float64, requires_grad=True)

## Evaluation

In [131]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()}")


Accuracy: 0.6662049889564514
