In [214]:
import torch
print(torch.__version__)

2.6.0+cu126


In [215]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
    print("GPU not avialable. Using CPU.")

GPU is available!
Using GPU : NVIDIA GeForce GTX 1650


## Creating A Tensor

In [216]:
# using empty

a = torch.empty(2,3)
a

tensor([[0.5734, 1.4325, 0.9792],
        [0.9839, 1.1703, 1.8865]])

In [217]:
# check type
type(a)


torch.Tensor

In [218]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [219]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [220]:
# using rand
torch.rand(2,3)

tensor([[0.5779, 0.8697, 0.1810],
        [0.2684, 0.4645, 0.4449]])

In [221]:
# use of seed
torch.rand(2,3)

tensor([[0.2798, 0.5553, 0.0276],
        [0.6125, 0.2266, 0.4251]])

In [222]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [223]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [224]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [225]:
# using arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [226]:
# using linspace
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [227]:
# using eye -> identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [228]:
# using full
torch.full((4,5), 4)

tensor([[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]])

## Tensor Shapes

In [229]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [230]:
x.shape

torch.Size([2, 3])

In [231]:
torch.empty_like(x)

tensor([[      4053924972400, 4607182418800017408, 4607182418800017408],
        [4607182418800017408, 4607182418800017408, 4607182418800017408]])

In [232]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [233]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [234]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [235]:
# find a data type
x 

tensor([[1, 2, 3],
        [4, 5, 6]])

In [236]:
x.dtype

torch.int64

In [237]:
# assigning data type
torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32).dtype

torch.float32

In [238]:
# using to()
x.to(torch.bool).dtype

torch.bool

## Mathematical Operations

1. Scalar Operations

In [239]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [240]:
x.dtype

torch.float32

In [241]:
# addition
x + 5

tensor([[5.7118, 5.7876],
        [5.4183, 5.9014]])

In [242]:
# subtraction
x - 5

tensor([[-4.2882, -4.2124],
        [-4.5817, -4.0986]])

In [243]:
# multiplication
x * 2

tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])

In [244]:
# division

x / 3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [245]:
# integer division
(x * 100) // 3

tensor([[23., 26.],
        [13., 30.]])

In [246]:
# mod
((x * 100) // 3) % 2


tensor([[1., 0.],
        [1., 0.]])

In [247]:
# power
x ** 10

tensor([[3.3371e-02, 9.1823e-02],
        [1.6403e-04, 3.5420e-01]])

2. Element wise Operations

In [248]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [249]:
# addition
a + b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [250]:
# subtraction

a - b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [251]:
# multiply

a * b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [252]:
# division

a / b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [253]:
# power
a ** b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [254]:
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [255]:
c = torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [256]:
# absolute
torch.abs(c)

tensor([1, 2, 3, 4])

In [257]:
# negative
torch.negative(c)

tensor([-1,  2, -3,  4])

In [258]:
d = torch.tensor([1.9,2.3,3.7,4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [259]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [260]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [261]:
# floor

torch.floor(d)

tensor([1., 2., 3., 4.])

In [262]:
# clamp
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction Operations

In [263]:
e = torch.randint(size=(2,3), low=0, high=10, dtype = torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [264]:
# sum 
torch.sum(e)

tensor(24.)

In [265]:
# sum along columns
torch.sum(e, dim = 0)

tensor([ 8.,  0., 16.])

In [266]:
# sum along rows
torch.sum(e, dim = 1)

tensor([15.,  9.])

In [267]:
# mean
torch.mean(e)

tensor(4.)

In [268]:
# mean along columns
torch.mean(e, dim = 0)

tensor([4., 0., 8.])

In [269]:
# mean along rows

torch.mean(e, dim = 1)

tensor([5., 3.])

In [270]:
# median 
torch.median(e)

tensor(0.)

In [271]:
# max
torch.max(e)

tensor(9.)

In [272]:
# min 
torch.min(e)

tensor(0.)

In [273]:
# product
torch.prod(e)

tensor(0.)

In [274]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [275]:
# variance
torch.var(e)

tensor(19.6000)

In [276]:
# argmax -> returns the index of maximum element
torch.argmax(e)

tensor(5)

In [277]:
# argmin
torch.argmin(e)

tensor(1)

4. Matrix Operations

In [278]:
f = torch.randint(size = (2,3), low = 0, high = 10)
g = torch.randint(size = (3,2), low = 0, high = 10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [279]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [280]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [281]:
# dot product
torch.dot(vector1,vector2)

tensor(11)

In [282]:
# transpose
f

tensor([[5, 7, 3],
        [9, 4, 0]])

In [283]:
torch.transpose(input=f,dim0=0,dim1=1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [284]:
h = torch.randint(size = (3,3), low = 0, high = 10, dtype = torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [285]:
# determinant
torch.det(h)

tensor(-110.0000)

In [286]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

5. Comparision Operations

In [287]:
i = torch.randint(size = (2,3), low = 0, high = 10)
j = torch.randint(size = (2,3), low = 0, high = 10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [288]:
# greater than
i > j

tensor([[ True,  True, False],
        [ True, False, False]])

In [289]:
# less than
i < j

tensor([[False, False,  True],
        [False,  True,  True]])

In [290]:
# equal to 
i == j

tensor([[False, False, False],
        [False, False, False]])

In [291]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [292]:
# greater than equal to 
i >= j

tensor([[ True,  True, False],
        [ True, False, False]])

In [293]:
# less than equal to 
i <= j

tensor([[False, False,  True],
        [False,  True,  True]])

6. Special Functions

In [294]:
k = torch.randint(size=(2,3), low = 0, high =10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [295]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [296]:
# exponent
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [297]:
# square root
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [298]:
# sigmoid
torch.sigmoid(k)


tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [299]:
# softmax
torch.softmax(k, dim =0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [300]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

## Inplace Operations

In [301]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [302]:
m + n    #In new memory location

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [303]:
m.add_(n)    #Inplace operations

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [304]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [305]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [306]:
torch.relu(m)    # In new memory location

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [307]:
m.relu_()     # Inplace operations

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [308]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying A Tensor

In [309]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [310]:
b = a

In [311]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [312]:
a[0][0] = 0

In [313]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [314]:
b     # The changes made in a are automatically happens in b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [315]:
id(a)

2375883173680

In [316]:
id(b)   # a and b points to same memory location

2375883173680

In [317]:
b = a.clone()

In [318]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [319]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [320]:
a[0][0] = 10


In [321]:
a

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [322]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [323]:
id(a)

2375883173680

In [324]:
id(b)

2375884830864

## Tensor Operations on GPU

In [325]:
torch.cuda.is_available()

True

In [326]:
device = torch.device("cuda")

In [327]:
# creating a new tensor on GPU

torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [328]:
# moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [329]:
a.to(device)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]], device='cuda:0')

In [330]:
# comparison of speed of exection of operation on GPU and CPU
import torch
import time

# define the size of the matrices
size =10000

# create random matrices on CPU
matrix_cpu1 = torch.rand(size,size)
matrix_cpu2 = torch.rand(size,size)

# measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2) # matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU : {cpu_time:.4f} seconds")


# move matrices to GPU
matrix_gpu1 = matrix_cpu1.to("cuda")
matrix_gpu2 = matrix_cpu2.to("cuda")


# measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2)
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")


# compare results
print("\n Speedup (CPU time / GPU time): ", cpu_time /gpu_time)

Time on CPU : 10.1326 seconds
Time on GPU: 0.0005 seconds

 Speedup (CPU time / GPU time):  19611.92662667282


## Reshaping Tensors

In [331]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [332]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [333]:
# flatten -> converts to 1D vector
a.flatten()   

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [334]:
b = torch.rand(2,3,4)
b

tensor([[[0.8881, 0.7989, 0.9514, 0.0141],
         [0.8903, 0.1649, 0.3162, 0.1331],
         [0.6763, 0.4254, 0.2375, 0.5430]],

        [[0.1174, 0.6532, 0.5115, 0.3094],
         [0.7907, 0.7351, 0.2693, 0.8009],
         [0.5839, 0.0061, 0.4671, 0.8243]]])

In [335]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [336]:
# unsqueeze  -> adds one extra dimension
c = torch.rand(226,226,3)
c.shape

torch.Size([226, 226, 3])

In [337]:
c.unsqueeze(dim = 0).shape

torch.Size([1, 226, 226, 3])

In [338]:
c.unsqueeze(dim = 1).shape

torch.Size([226, 1, 226, 3])

In [339]:
# squeeze -> removes one extra dimension
d = torch.rand(1,20)
d

tensor([[0.6899, 0.9883, 0.2160, 0.4054, 0.5001, 0.2665, 0.4164, 0.0810, 0.5344,
         0.3673, 0.9286, 0.0528, 0.3753, 0.2057, 0.5643, 0.4419, 0.5215, 0.6743,
         0.0401, 0.7158]])

In [340]:
d.shape

torch.Size([1, 20])

In [341]:
d.squeeze(dim = 0)

tensor([0.6899, 0.9883, 0.2160, 0.4054, 0.5001, 0.2665, 0.4164, 0.0810, 0.5344,
        0.3673, 0.9286, 0.0528, 0.3753, 0.2057, 0.5643, 0.4419, 0.5215, 0.6743,
        0.0401, 0.7158])

In [342]:
d.squeeze(dim = 0).shape

torch.Size([20])

## NumPy and PyTorch

In [343]:
import numpy as np

In [344]:
a = torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [345]:
b = a.numpy()     #converts tensor to numpy array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [346]:
type(b)

numpy.ndarray

In [347]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [348]:
d = torch.from_numpy(c)   #converts numpy array to tensor
d

tensor([1, 2, 3])

In [349]:
type(d)

torch.Tensor