## What is NumPy?

NumPy(Numerical Python) is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and metrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.\
At the core of the NumPy package, is the ndarray object. This encapsualtes n-dimensional arrays of homogeneous data types.

## NumPy Arrays Vs Python Sequences

* NumPy arrays have a fixed size at creation, unlike Python lists(which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory (homogeneous data types).
* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python's built-in sequences.
* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; through these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Creating NumPy Arrays

In [605]:
import numpy as np

In [606]:
arr1 = np.array([1,2,3])   #1D array or Vector
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [607]:
arr2 = np.array([[1,2,3],[4,5,6]])  #2D array or Matrix
print(arr2)

[[1 2 3]
 [4 5 6]]


In [608]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #3D array Or Tensor
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [609]:
# dtype
np.array([1,2,3],dtype=float)
np.array([0,1,2,3],dtype=bool)

array([False,  True,  True,  True])

In [610]:
# np.arange
np.arange(1,11)  

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [611]:
# with reshape
np.arange(1,11).reshape(5,2) #5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [612]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [613]:
# np.ones 
np.ones((3,4),dtype=int)     #It receives the tuple of shapes as parameter

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [614]:
# np.zeros
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [615]:
# np.random
np.random.random((3,4))    #Intialize the random numbers between 0 and 1
# Here first random is class and second random is method of random class

array([[0.8867457 , 0.89741909, 0.14936755, 0.55960234],
       [0.5360214 , 0.15724541, 0.49177188, 0.68578485],
       [0.19016395, 0.4842319 , 0.27511768, 0.51130976]])

In [616]:
# np.linspace (linear space)
np.linspace( start = -10,stop = 10,num = 10, dtype=int, endpoint=True)     # Generates linearly space numbers betwwen given range


array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [617]:
# np.identity
np.identity(3,dtype=int)   #Creates a identity matrix of order 3


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Array Attributes/Properties


In [618]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [619]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [620]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [621]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [622]:
# ndim = Number of Dimension
a1.ndim
a2.ndim
a3.ndim

3

In [623]:
# shape = Number of items in each dimension
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [624]:
# size = Total Number of items
a1.size
a2.size
a3.size

8

In [625]:
#itemsize = size of each item in memory
a1.itemsize
a2.itemsize
a3.itemsize

8

In [626]:
#dtype = Items datatype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


## Changing Datatype

In [627]:
#astype
a3.dtype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operations


In [628]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(start=12,stop=24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [629]:
# Scalar Operations 

#1. Arithmetic Operators like addition, subtraction, division, multiplication

a1*2   #Here 2 is a scalar

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [630]:
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [631]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [632]:
#2. Relational operators like equals to, greater than, lesser than e.t.c

a2 > 6

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [633]:
a2 > 16

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [634]:
# Vector Operations

#1. Arithmetic operators like addition, subraction, multiplication  between corresponding elements

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [635]:
a1 * a2 

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

## Array Functions


In [636]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[51., 10., 44.],
       [ 4., 86., 50.],
       [12., 17., 54.]])

In [637]:
# max
# 0 -> column
# 1 -> row
np.max(a1)
np.max(a1, axis=1)
np.max(a1, axis=0)

array([51., 86., 54.])

In [638]:
# min
np.min(a1)

np.float64(4.0)

In [639]:
# sum
np.sum(a1)

np.float64(328.0)

In [640]:
# prod
np.prod(a1)

np.float64(4251823488000.0)

In [641]:
# mean
np.mean(a1)
np.mean(a1, axis =1)

array([35.        , 46.66666667, 27.66666667])

In [642]:
# median
np.median(a1)

np.float64(44.0)

In [643]:
# standard deviation
np.std(a1)

np.float64(25.699594078554416)

In [644]:
# variance
np.var(a1)

np.float64(660.4691358024692)

In [645]:
# trignometric functions
np.sin(a1)     #sine of each items

array([[ 0.67022918, -0.54402111,  0.01770193],
       [-0.7568025 , -0.92345845, -0.26237485],
       [-0.53657292, -0.96139749, -0.55878905]])

In [646]:
# dot product(.)
a2 =np.arange(12).reshape(3,4)     #Number of columns of the first matrix should be equal to number of rows of second matrix
a3 =np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [647]:
# log 
np.log(a1)    # Returns a log of each item in a array

array([[3.93182563, 2.30258509, 3.78418963],
       [1.38629436, 4.4543473 , 3.91202301],
       [2.48490665, 2.83321334, 3.98898405]])

In [648]:
# exponents
np.exp(a1)

array([[1.40934908e+22, 2.20264658e+04, 1.28516001e+19],
       [5.45981500e+01, 2.23524660e+37, 5.18470553e+21],
       [1.62754791e+05, 2.41549528e+07, 2.83075330e+23]])

In [649]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[60., 30., 41.],
       [ 4., 86., 51.]])

## Indexing & Slicing

In [650]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [651]:
#Indexing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [652]:
a1[0] #first item

np.int64(0)

In [653]:
a1[-1]  #last item

np.int64(9)

In [654]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [655]:
a2[1,2]

np.int64(6)

In [656]:
a2[0,1]

np.int64(1)

In [657]:
a2[-1,-1]

np.int64(11)

In [658]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [659]:
a3[1,0,1]     #a3[3rd dimension,row,column]

np.int64(5)

In [660]:
a3[0,1,0]

np.int64(2)

In [661]:
a3[0,0,0]

np.int64(0)

In [662]:
a3[-1,-1,-1]

np.int64(7)

In [663]:
#Slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [664]:
a1[2:5]    

array([2, 3, 4])

In [665]:
a1[-4:-1]

array([6, 7, 8])

In [666]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [667]:
a2[0,:]  # first row

array([0, 1, 2, 3])

In [668]:
a2[:,2] # 3rd column

array([ 2,  6, 10])

In [669]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [670]:
a2[-2:,-3:-1]

array([[ 5,  6],
       [ 9, 10]])

In [671]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [672]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [673]:
a2[1,::3]

array([4, 7])

In [674]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [675]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [676]:
a3[:,:1,:]

array([[[0, 1]],

       [[4, 5]]])

In [677]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [678]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [679]:
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [680]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [681]:
a3[0,1]

array([3, 4, 5])

In [682]:
a3[1,:,1]

array([10, 13, 16])

In [683]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [684]:
a3[-1,1:,1:]

array([[22, 23],
       [25, 26]])

In [685]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [686]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [687]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [688]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [689]:
for i in a2:   #prints each row
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [690]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [691]:
a3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [692]:
for i in a3: #prints each 2D array
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [693]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [694]:
# reshape
a1 = np.arange(12)
a1 = a1.reshape((3,4))
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [695]:
# transpose    # alters rows and columns
np.transpose(a1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [696]:
a1.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [697]:
#ravel   #coverts the array of any dimension into 1D

In [698]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [699]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [700]:
# horizontal stacking  -> rows remains same
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [701]:
np.hstack((a4,a5))   #tuple of array as parameter

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [702]:
#vertical stacking    -> columns remains same
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [703]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [704]:
np.hsplit(a4,2)    #array and number of equal parts as parameters

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [705]:
# vertical splitting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]