In [16]:
import numpy as np

np.sort\
Return a sorted copy of an array.

In [17]:
a = np.random.randint(low=1,high=100,size=15)
a

array([68, 81, 85, 74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4],
      dtype=int32)

In [18]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[82, 78, 47, 89],
       [50, 28, 52, 21],
       [89, 24, 57, 77],
       [85, 39, 11, 95],
       [95, 70, 92, 24],
       [49, 32, 58, 84]], dtype=int32)

In [19]:
np.sort(a)  #sort in ascending order by default

array([ 4,  7, 13, 16, 27, 30, 38, 42, 67, 68, 73, 74, 81, 85, 93],
      dtype=int32)

In [ ]:
np.sort(a)[::-1]  #sort in descending order

array([93, 85, 81, 74, 73, 68, 67, 42, 38, 30, 27, 16, 13,  7,  4],
      dtype=int32)

In [21]:
np.sort(b)   #sort the elements of each row

array([[47, 78, 82, 89],
       [21, 28, 50, 52],
       [24, 57, 77, 89],
       [11, 39, 85, 95],
       [24, 70, 92, 95],
       [32, 49, 58, 84]], dtype=int32)

In [22]:
np.sort(b, axis=0) #sort the elements of each row

array([[49, 24, 11, 21],
       [50, 28, 47, 24],
       [82, 32, 52, 77],
       [85, 39, 57, 84],
       [89, 70, 58, 89],
       [95, 78, 92, 95]], dtype=int32)

np.append\
The numpy.append() appends values along the mentioned axis at the end of the array.

In [23]:
a

array([68, 81, 85, 74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4],
      dtype=int32)

In [24]:
np.append(a,200)

array([ 68,  81,  85,  74,  27,  38,  16,  13,  30,  67,  93,  42,  73,
         7,   4, 200])

In [25]:
b

array([[82, 78, 47, 89],
       [50, 28, 52, 21],
       [89, 24, 57, 77],
       [85, 39, 11, 95],
       [95, 70, 92, 24],
       [49, 32, 58, 84]], dtype=int32)

In [28]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[82., 78., 47., 89.,  1.],
       [50., 28., 52., 21.,  1.],
       [89., 24., 57., 77.,  1.],
       [85., 39., 11., 95.,  1.],
       [95., 70., 92., 24.,  1.],
       [49., 32., 58., 84.,  1.]])

np.concatenate\
The np.concatenate() function concatenate a sequence of arrays along an existing axis.

In [30]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [31]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique\
With the help of np.unique() method, we can get the unique values from an array given as a parameter in np.unique() method.

In [34]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [35]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

np.expand_dims\
With the help of np.expand_dims() method, we can get the expanded dimensions of an array.

In [ ]:
a

array([68, 81, 85, 74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4],
      dtype=int32)

In [39]:
a.shape

(15,)

In [37]:
np.expand_dims(a,axis=0)

array([[68, 81, 85, 74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4]],
      dtype=int32)

In [40]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [38]:
np.expand_dims(a,axis=1)

array([[68],
       [81],
       [85],
       [74],
       [27],
       [38],
       [16],
       [13],
       [30],
       [67],
       [93],
       [42],
       [73],
       [ 7],
       [ 4]], dtype=int32)

In [41]:
np.expand_dims(a,axis=1).shape

(15, 1)

np.where\
The np.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [42]:
a

array([68, 81, 85, 74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4],
      dtype=int32)

In [43]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  2,  3,  9, 10, 12]),)

In [44]:
# replace all values greater than 50 with 0
np.where(a>50,0,a)

array([ 0,  0,  0,  0, 27, 38, 16, 13, 30,  0,  0, 42,  0,  7,  4],
      dtype=int32)

In [45]:
# replace all even numbers with 0
np.where(a % 2 == 0, 0, a)

array([ 0, 81, 85,  0, 27,  0,  0, 13,  0, 67, 93,  0, 73,  7,  0],
      dtype=int32)

np.argmax\
The np.argmax() function returns indices of the max element of the array in a particular axis.

In [46]:
a

array([68, 81, 85, 74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4],
      dtype=int32)

In [47]:
np.argmax(a)

np.int64(10)

In [48]:
b

array([[82, 78, 47, 89],
       [50, 28, 52, 21],
       [89, 24, 57, 77],
       [85, 39, 11, 95],
       [95, 70, 92, 24],
       [49, 32, 58, 84]], dtype=int32)

In [49]:
np.argmax(b,axis=0)

array([4, 0, 4, 3])

In [50]:
np.argmax(b,axis=1)

array([3, 2, 0, 3, 0, 3])

np.argmin\
The np.argmin() function returns indices of the min element of the array in a particular axis.

In [51]:
a

array([68, 81, 85, 74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4],
      dtype=int32)

In [52]:
np.argmin(a)

np.int64(14)

In [53]:
b

array([[82, 78, 47, 89],
       [50, 28, 52, 21],
       [89, 24, 57, 77],
       [85, 39, 11, 95],
       [95, 70, 92, 24],
       [49, 32, 58, 84]], dtype=int32)

In [54]:
np.argmin(b,axis=0)

array([5, 2, 3, 1])

In [55]:
np.argmin(b,axis=1)

array([2, 3, 1, 2, 3, 1])

np.cumsum\
The np.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [56]:
a

array([68, 81, 85, 74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4],
      dtype=int32)

In [57]:
np.cumsum(a)

array([ 68, 149, 234, 308, 335, 373, 389, 402, 432, 499, 592, 634, 707,
       714, 718])

In [58]:
b

array([[82, 78, 47, 89],
       [50, 28, 52, 21],
       [89, 24, 57, 77],
       [85, 39, 11, 95],
       [95, 70, 92, 24],
       [49, 32, 58, 84]], dtype=int32)

In [60]:
np.cumsum(b)

array([  82,  160,  207,  296,  346,  374,  426,  447,  536,  560,  617,
        694,  779,  818,  829,  924, 1019, 1089, 1181, 1205, 1254, 1286,
       1344, 1428])

In [59]:
np.cumsum(b, axis=0)

array([[ 82,  78,  47,  89],
       [132, 106,  99, 110],
       [221, 130, 156, 187],
       [306, 169, 167, 282],
       [401, 239, 259, 306],
       [450, 271, 317, 390]])

In [61]:
np.cumsum(b, axis=1)

array([[ 82, 160, 207, 296],
       [ 50,  78, 130, 151],
       [ 89, 113, 170, 247],
       [ 85, 124, 135, 230],
       [ 95, 165, 257, 281],
       [ 49,  81, 139, 223]])

np.cumprod\
The np.cumprod() function is used when we want to compute the cumulative product of array elements over a given axis.

In [62]:
a

array([68, 81, 85, 74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4],
      dtype=int32)

In [63]:
np.cumprod(a)

array([                  68,                 5508,               468180,
                   34645320,            935423640,          35546098320,
               568737573120,        7393588450560,      221807653516800,
          14861112785625600,  1382083489063180800,  2707274319524938752,
       -5283159485484538880,   -88628250972668928,  -354513003890675712])

np.percentile\
The np.percentile() function is used to compute nth percentile of the given data(array elements) along the specified axis.

Percentile(x) = (Number of values fall under 'x'/Total number of values) * 100

In [64]:
a

array([68, 81, 85, 74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4],
      dtype=int32)

In [65]:
np.percentile(a,100)

np.float64(93.0)

In [66]:
np.percentile(a,0)

np.float64(4.0)

In [67]:
np.percentile(a,50)

np.float64(42.0)

In [68]:
np.median(a)

np.float64(42.0)

np.histogram\
NumPy has built-in np.histogram() function which represents the frequency of data distribution in the graphical form.

In [69]:
a

array([68, 81, 85, 74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4],
      dtype=int32)

In [74]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 2, 1, 2, 1, 0, 2, 2, 2, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [75]:
np.histogram(a,bins=[0,50,100])

(array([8, 7]), array([  0,  50, 100]))

np.corrcoef\
Returns Pearson product-moment correlation coefficients.

In [76]:
salary =np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1,3,2,4,2])

In [77]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin\
With the help of np.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [78]:
a

array([68, 81, 85, 74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4],
      dtype=int32)

In [79]:
items = [0,10,20,30,40,50,60,70,80,90,100]

np.isin(a,items)

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False])

In [80]:
a[np.isin(a,items)]

array([30], dtype=int32)

np.flip\
The np.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [81]:
a

array([68, 81, 85, 74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4],
      dtype=int32)

In [82]:
np.flip(a)

array([ 4,  7, 73, 42, 93, 67, 30, 13, 16, 38, 27, 74, 85, 81, 68],
      dtype=int32)

In [83]:
b

array([[82, 78, 47, 89],
       [50, 28, 52, 21],
       [89, 24, 57, 77],
       [85, 39, 11, 95],
       [95, 70, 92, 24],
       [49, 32, 58, 84]], dtype=int32)

In [ ]:
np.flip(b)   # flips in both rows and columns

array([[84, 58, 32, 49],
       [24, 92, 70, 95],
       [95, 11, 39, 85],
       [77, 57, 24, 89],
       [21, 52, 28, 50],
       [89, 47, 78, 82]], dtype=int32)

In [85]:
np.flip(b,axis=0)

array([[49, 32, 58, 84],
       [95, 70, 92, 24],
       [85, 39, 11, 95],
       [89, 24, 57, 77],
       [50, 28, 52, 21],
       [82, 78, 47, 89]], dtype=int32)

In [86]:
np.flip(b,axis=1)

array([[89, 47, 78, 82],
       [21, 52, 28, 50],
       [77, 57, 24, 89],
       [95, 11, 39, 85],
       [24, 92, 70, 95],
       [84, 58, 32, 49]], dtype=int32)

np.put\
The np.put() method replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [87]:
a

array([68, 81, 85, 74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4],
      dtype=int32)

In [88]:
np.put(a,[0,1],[680,810])

In [89]:
a

array([680, 810,  85,  74,  27,  38,  16,  13,  30,  67,  93,  42,  73,
         7,   4], dtype=int32)

np.delete\
The np.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [90]:
a

array([680, 810,  85,  74,  27,  38,  16,  13,  30,  67,  93,  42,  73,
         7,   4], dtype=int32)

In [91]:
np.delete(a,0)

array([810,  85,  74,  27,  38,  16,  13,  30,  67,  93,  42,  73,   7,
         4], dtype=int32)

In [92]:
a

array([680, 810,  85,  74,  27,  38,  16,  13,  30,  67,  93,  42,  73,
         7,   4], dtype=int32)

In [93]:
np.delete(a,[0,1,2])

array([74, 27, 38, 16, 13, 30, 67, 93, 42, 73,  7,  4], dtype=int32)

Set Functions
   * np.union1d
   * np.intersect1d
   * np.setdiff1d
   * np.setxor1d
   * np.in1d

In [94]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [95]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [96]:
np.intersect1d(m,n)

array([3, 4, 5])

In [97]:
np.setdiff1d(m,n)

array([1, 2])

In [ ]:
np.setxor1d(m,n)   #removes the common elements

array([1, 2, 6, 7])

In [102]:
np.in1d(m,1)

C:\Users\sanje\AppData\Local\Temp\ipykernel_11112\3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

In [104]:
m[np.in1d(m,1)]

C:\Users\sanje\AppData\Local\Temp\ipykernel_11112\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

In [105]:
np.in1d(m,20)

C:\Users\sanje\AppData\Local\Temp\ipykernel_11112\212122365.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,20)


array([False, False, False, False, False])

np.clip\
The np.clip() function is used to clip(limit) the values in an array.

In [106]:
a

array([680, 810,  85,  74,  27,  38,  16,  13,  30,  67,  93,  42,  73,
         7,   4], dtype=int32)

In [107]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 74, 27, 38, 25, 25, 30, 67, 75, 42, 73, 25, 25],
      dtype=int32)